name: Projet # The name of the workflow, visible in the GitHub Actions tab.

on:
  push:
    branches:
      - main # Runs only if changes are pushed to the 'main' branch.
  pull_request:

jobs:
  build-and-test: # The name of the job.
    runs-on: ubuntu-latest # Specifies the virtual machine environment for the job.

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code # Descriptive name for the step.
        uses: actions/checkout@v3 # Uses a prebuilt GitHub Action to clone the repo into the VM.

      # Step 2: Install necessary dependencies
      - name: Install build essentials # Install necessary tools, including g++
        run: sudo apt-get update && sudo apt-get install -y g++

      # Step 3: Compile the C++ program
      - name: Build the program
        run: g++ -o ProjetV1 ProjetV1.cpp

      # Step 4: Run the compiled program
      - name: Run the test # Executes the compiled C++ program to perform the tests.
        run: ./ProjetV1

      # Step 5: Check for test failures
      - name: Check test result
        if: failure()
        run: exit 1
